### ISSUE TITLE
Lepsi logo PP

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#1]
V hlavicce je potreba udelat logo v pruhlednem PNG

<img width="308" alt="screen shot 2015-08-13 at 19 31 08" src="https://cloud.githubusercontent.com/assets/4248287/9256794/eb4d8afe-41f1-11e5-9881-6f5c62479e14.png">

**Comment by pavelkraleu** [comment]
![institute_of_cryptoanarchy](https://cloud.githubusercontent.com/assets/4248287/9342446/fb22008c-45fb-11e5-8412-a08b8f82567d.png)

**Comment by tomtomklima** [comment]
done, zavírám
