### ISSUE TITLE
Font s háčky

### ISSUE THREAD

**Issue by tomtomklima** [ParalelniPolis/hcpp2015main#10]
problém s diakritikou - konrkétně "zatím" jen u nadpisu u programu, - "NEDĚLE" má Ě jinak - není to moc viděl, ale stejně...

**Comment by pavelkraleu** [comment]
Mel jsem stejny problem na webu Paper Hubu, dal jsem tam jiny font.

Puvodni CSS Orlando 
http://orlando.html.themeforest.createit.pl/light/assets/css/style.css
Upraveny CSS
http://paperhub.cz/assets/css/style.css

Zmena je na druhem radku, kde je misto fontu Lato, pouzit font Roboto
`@import url(http://fonts.googleapis.com/css?family=Roboto:300,400,700,900,300italic,400italic,700italic,900italic|Open+Sans:400italic,600italic,700italic,800italic,400,600,700,800&subset=latin,latin-ext,cyrillic-ext,greek-ext,greek,vietnamese,cyrillic);`

**Comment by pavelkraleu** [comment]
A jeste se v CSS musi na par mistech prepsat Lato na Roboto

**Comment by pavelkraleu** [comment]
cc @tomtomklima

**Comment by tomtomklima** [comment]
@pavelkraleu Díky! Fixed
