### ISSUE TITLE
Tablet & Mobile view timer

### ISSUE THREAD

**Issue by MarekJCK** [ParalelniPolis/hcpp2015main#11]
https://www.dropbox.com/s/brjfdt881mfjt1v/Screenshot%202015-08-19%2000.06.56.png?dl=0
- Prehodit minuty pod dny aby boli vo stvorici a vycentrovat na stred. 

https://www.dropbox.com/s/2nrp48ah2rhq08a/Screenshot%202015-08-19%2000.09.05.png?dl=0
- Mobile len vycentrovat na stred.

**Comment by tomtomklima** [comment]
Sorry, tohle nedám, musí se hrábnout do javascriptu

**Comment by MarekJCK** [comment]
Toto je iba positioning a media view. Dnes to opravim.

**Comment by MarekJCK** [comment]
https://www.dropbox.com/s/zami65uax8yg4d1/Screenshot%202015-08-19%2022.56.20.png?dl=0

Na desktop & tablet staci odpalkovat v style.css v triede .counter-block element padding-left: 40px; a bude to vyzerat dobre. 

Skuste si to len odobrat cez inspect element a pozriet velkosti. Od  1220px do 603px to vyzera fajn podla mna.

**Comment by tomtomklima** [comment]
@MarekJCK můžeš to pls fixnout?

**Comment by MarekJCK** [comment]
Okay

**Comment by MarekJCK** [comment]
https://www.dropbox.com/s/5pmi49crhow1vv7/Screenshot%202015-09-03%2023.27.31.png?dl=0
https://www.dropbox.com/s/9wypql7krabw7pa/Screenshot%202015-09-03%2023.28.38.png?dl=0
Tomasi vyzera to tak ze nemam permission to push to this repo. Bud ma pridaj alebo len urob v cssku co som hore napisal v komente. Tablet cize pod 603px opravim neskor.

**Comment by pavelkraleu** [comment]
@MarekJCK Pridal jsem te to Organizace PP, nevim proc si tam nebyl. Pred par dny zahadne zmizela Iva stejnym zpusobem...

**Comment by MarekJCK** [comment]
Diky Pavel. Urobim jednu zmenu teraz a poladim to.

**Comment by pavelkraleu** [comment]
Super :) Musis si odkliknout potvrzeni co mas v mailu

**Comment by MarekJCK** [comment]
Hele nic mi neprislo. Neviem ci som retardovany alebo to nevidim...:)

**Comment by pavelkraleu** [comment]
Poslal jsem to jeste jednou

**Comment by MarekJCK** [comment]
Tak skus pozriet if you like what I pushed Palko

**Comment by MarekJCK** [comment]
Hele za mne dobry tak zavieram bug. Sorry za tie commity nevedel som rozchodit webserver. Pa
