### ISSUE TITLE
Facebook Opengraph

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#12]
Rozchodit Facbeook Opengraph, alespon tak jak je to na Webu 1.0 

https://github.com/ParalelniPolis/hcpp2015/blob/gh-pages/index.html#L40
<img width="516" alt="screen shot 2015-08-19 at 00 46 15" src="https://cloud.githubusercontent.com/assets/4248287/9344837/e92382b0-460b-11e5-9242-723c02d654c1.png">

**Comment by tomtomklima** [comment]
Eh, kam? V návrhu jsem nic podobného nepotkal (dole je funkční miničtereček jako odkaz na FB)

**Comment by pavelkraleu** [comment]
Tome, pro tohle potrebujeme rozchodit DNS tak jak si to udelal s domenou new.hcpp.cz.
Tedy, CNAME na paralelnipolis.github.io.
cc @tomtomklima

**Comment by tomtomklima** [comment]
Jasný, a na jakou doménu? facebook.hcpp.cz? @pavelkraleu

**Comment by pavelkraleu** [comment]
na domenu hcpp.cz

new.hcpp.cz nyni vypada takto a je dostupny pro Facebook :

```
;; ANSWER SECTION:
new.hcpp.cz.        3599    IN  CNAME   paralelnipolis.github.io.
paralelnipolis.github.io. 3599  IN  CNAME   github.map.fastly.net.
github.map.fastly.net.  15  IN  A   23.235.43.133
```

hcpp.cz furt vypada takto a je tak nedostupny pro Facebook (nenasleduje 302)

```
;; ANSWER SECTION:
hcpp.cz.        3599    IN  A   192.30.252.153
hcpp.cz.        3599    IN  A   192.30.252.154
```

**Comment by tomtomklima** [comment]
Sorry, byl jsem rozespalý, změněno

**Comment by tomtomklima** [comment]
Aha, tak neuložilo - ptal jsem se a napsali mi že to nelze pro domény druhého řádku změnit - můžu to přervat přes A záznam nebo to celé přesuneme na adresu 2015.hcpp.cz (jak jsme už plánovali) @pavelkraleu

**Comment by tomtomklima** [comment]
@pavelkraleu ?

**Comment by pavelkraleu** [comment]
CNAME pro domenu druheho radu opravdu nelze
http://serverfault.com/questions/430970/cname-for-top-of-domain

**Comment by pavelkraleu** [comment]
@tomtomklima muzes prosim nastavit CNAME pro www.hcpp.cz na paralelnipolis.github.io. tak jako si to uz delal ?
Github pages nam automaticky udela redirect hcpp.cz -> www.hcpp.cz a bude vymalovano
https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/#configuring-a-www-subdomain

**Comment by tomtomklima** [comment]
mas

**Comment by pavelkraleu** [comment]
Fixed, diky Tomasi za pomoc

![screen shot 2015-09-18 at 17 00 50](https://cloud.githubusercontent.com/assets/4248287/9962618/ed9e745c-5e26-11e5-8e7e-cc244faefbfa.png)
