### ISSUE TITLE
Doplnit medailonky

### ISSUE THREAD

**Issue by tomtomklima** [ParalelniPolis/hcpp2015main#14]
ve složce persons jsou dvě hotová html (tempelhof.html a ulbricht.html) - ideálně ty překopírovat, pojmenovat příjmením bez diakritiky a přepsat správnými informacemi

**Comment by pavelkraleu** [comment]
Vetsina medailonku je hotova, udealal jsem nekolik ticketu pro jednotlive osoby kde potrebujeme doplnit udaje
