### ISSUE TITLE
zobrazení mapy

### ISSUE THREAD

**Issue by tomtomklima** [ParalelniPolis/hcpp2015main#18]
Nezobrazuje se mapa na github.io, na localhostu mě ano

**Comment by tomtomklima** [comment]
Zkusil jsem, nevyřešil jsem. @pavelkraleu ?

**Comment by pavelkraleu** [comment]
Vidim ji normalne, jak presne se to projevuje ?
<img width="1280" alt="screen shot 2015-08-23 at 23 20 56" src="https://cloud.githubusercontent.com/assets/4248287/9430241/b2cf5ee2-49ed-11e5-8f28-6ab07fff19c4.png">

**Comment by tomtomklima** [comment]
Mě se nezobrazuje (je tam jen lišta o velikosti 1px (což je možný že to blokuje adblock si těď uvědomuju) a mfish si stěžoval na to že mu taky není vidět

**Comment by tomtomklima** [comment]
Vida, nevím čím ale už funguje... closing
