### ISSUE TITLE
Fotka v hlavicce webu

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#2]
Sehnat fotku do hlavicky

<img width="1182" alt="screen shot 2015-08-13 at 19 31 12" src="https://cloud.githubusercontent.com/assets/4248287/9256801/0b3f8664-41f2-11e5-98f8-69c1fa80d532.png">

**Comment by tomtomklima** [comment]
Vidím že hotovo, odškrtávám
