### ISSUE TITLE
Rozchodit tlacitko na zmenu jazyka

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#23]
<img width="257" alt="screen shot 2015-08-27 at 14 21 54" src="https://cloud.githubusercontent.com/assets/4248287/9520378/02c48978-4cc7-11e5-87fb-f0b5cae235fa.png">

**Comment by tomtomklima** [comment]
Přidáno, ale neumím si poradit s tím překladem - v anglické verzi se nezobrazilo. To bude asi na tebe @pavelkraleu
