### ISSUE TITLE
Prenastavit DNS za ucelem rozchchozeni FB Opengraphu 

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#25]
Nastavit DNS takto :

Your DNS isn't set up correctly:

› dig new.hcpp.cz  
;new.hcpp.cz.           IN  A
new.hcpp.cz.        3580    IN  A   192.30.252.153
new.hcpp.cz.        3580    IN  A   192.30.252.154

Instead of two A records for the new.hcpp.cz subdomain, you should have one CNAME record set up that points at paralelnipolis.github.io.

**Comment by tomtomklima** [comment]
done
