### ISSUE TITLE
Sekce hostu - obecne pripominky

### ISSUE THREAD

**Issue by sipak** [ParalelniPolis/hcpp2015main#26]
1) sekce hostu je zbytecne mega, fotky jsou obrovske a nekvalitni > cele by to melo byt mensi, nevyjizdejme s fotkama z sirky ostatniho textu, fotky zmenseme tak, aby zachovavali okraje textu nad a pod.
2) stejnoceni fotografii se vetsinou dosahuje tim, ze se jim da stejny odstin, napr. greyscale
3) po kliknuti na hosta me to vede na jinou stranku, ktera je uplne mimo > prohlizeni jednotlivych hostu bude utrpeni

**Comment by pavelkraleu** [comment]
Je to podle zadani od mFishe, viz zejmena soubory korektura*
https://github.com/ParalelniPolis/hcpp2015main/tree/gh-pages/zadani

**Comment by evapytlounova** [comment]
ja mam k sekci hoste taky postreh - kdyz zmensim celou stranku zoomem (chromium), tak se vsechno pekne scaluje, ale obrazky zustavaji stale stejne velke. Asi chapu proc to tak je, ale jen rikam, ze to vypada divne

**Comment by sipak** [comment]
co se tyka velikosti a sirky fotografii, tak v navrhu jsou fotky umernejsi a jen o trochu presahuji velikost sirky texty... na sirokouhlem monitoru je to proste zabijak, melo by tam byt nejake omezeni na nejvetsi moznou velikost

**Comment by evapytlounova** [comment]
+1 (navrh: mne prijde rozumne omezit sirku obrazku na cca 300px a pocet na radku na 3 (nebo 4))

**Comment by tomtomklima** [comment]
Zkuste jak to bude vypadat - se třeba řadama max souhlasím, ale mě se na mobilním zobrazení velké obrázky líbí

**Comment by evapytlounova** [comment]
vsak i kdyz bude omezeni na tri rady a max sirku, tak na mobilu budou velke, ne? ;)

**Comment by tomtomklima** [comment]
No však právě ;)

**Comment by tomtomklima** [comment]
Fixnuto - je max 5 sloupců, přidal jsem jednu kotvu na zobrazování dvou fotek vedle sebe. Všechno ostatní je myslím passe
