### ISSUE TITLE
Uvodni strana

### ISSUE THREAD

**Issue by sipak** [ParalelniPolis/hcpp2015main#27]
chybi tema kongresu Blackout a nejaky claim "Prepare for the future after Blackout", "Future will be decentralized" ... etc. >>> kdyz prijdu na titulni stranu nevim, proc bych mel kliknout na pokracovat dolu, stranka nic zajimaveho krome toho, ze bude kongres nerika, gradient v pozadi divne plastikovy, celkove je to ponury a nelakavy, modra (0,0,255) je tam schvalne? je to dost velky nasili...

**Comment by pavelkraleu** [comment]
Viz zadani https://github.com/ParalelniPolis/hcpp2015main/tree/gh-pages/zadani

**Comment by evapytlounova** [comment]
ta modra je dost divoka i na me. Plus horni prechod "cerna | modra | bila" me vylozene nici... ale zas ja tomu nerozumim a v zadani to tak je, takze proste jen rikam

**Comment by tomtomklima** [comment]
btw ta modrá je myslím 0002FF :)
