### ISSUE TITLE
divny scroll pri navraceni na stranku

### ISSUE THREAD

**Issue by evapytlounova** [ParalelniPolis/hcpp2015main#28]
repro steps:
1 sescrolovat uplne dolu
2 klick youtube/ facebook/ twitter - otevre se ve stejnem okne
3 go back - stranka se podivne scrollne do schedule sekce

optimalne by mela zustat dole, tedy v sekci contact

(lin 3.13/ chromium)

**Comment by pavelkraleu** [comment]
Tohle by slo vyresit oteviranim socialnich siti v novem tabu

**Comment by evapytlounova** [comment]
jop, to by bylo imho nejsnazsi reseni (a navic je to plus samo o sobe)

**Comment by pavelkraleu** [comment]
Done
