### ISSUE TITLE
Menu pri zmensovani obrazovku skace pod nadpis

### ISSUE THREAD

**Issue by evapytlounova** [ParalelniPolis/hcpp2015main#29]
pri resizu chromia se horni menu prekryva s napisem HCPP15 + continue sipka pro scroll do dalsi sekce chybi 
(lin 3.13/ chromium)

![polisweb_continue](https://cloud.githubusercontent.com/assets/14018808/9552084/b1f0b66c-4db5-11e5-918c-2e8e6a702f6c.png)

**Comment by evapytlounova** [comment]
- horni menu umi zmizet uplne, pokud stranka neni dostatecne siroka 

![image](https://cloud.githubusercontent.com/assets/14018808/9553034/b2d7e63e-4dbc-11e5-8489-3085b4aea3d6.png)

jinak na win/chrome se mi texty prekryt nepodarilo (ale issue se sipkou a mizicim menu je tu taky)

**Comment by evapytlounova** [comment]
tak uz jsem si vsmla toho skryvajiciho se menu (ale ted mozna by tam misto obrazku mohlo byt napsane 'menu'?), takze tohle je ok

**Comment by pavelkraleu** [comment]
Pri resizovani to opravdu dela zajimave veci, menu skace pod nadpis atp
<img width="812" alt="screen shot 2015-08-29 at 23 10 21" src="https://cloud.githubusercontent.com/assets/4248287/9564313/3452cf4e-4ea3-11e5-8694-2754e653a101.png">

**Comment by tomtomklima** [comment]
Fixnuto - zkrátil jsem nadpisy
