### ISSUE TITLE
Pocitadlo na hlavni strance

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#3]
Nastavit pocitadlo na spravny cas a opravit prvni cislici kde je 0 a 8 v jednom poli

<img width="1061" alt="screen shot 2015-08-13 at 19 32 53" src="https://cloud.githubusercontent.com/assets/4248287/9256822/33f020dc-41f2-11e5-9f10-90c9c2dd048f.png">

**Comment by MarekJCK** [comment]
I did repair the counter in days. There was 0 in JavaScript. It is working properly now.

**Comment by tomtomklima** [comment]
Díky! V čem to bylo jestli se můžu zeptat?

**Comment by MarekJCK** [comment]
Javascript mal nastavenu default 0. Stacilo ju iba odmazat. Nespominam si teraz presne kde. Ale najdem ak to chces vediet do detaiilu ;)
