### ISSUE TITLE
obrazek v pozadi se pri resizu necentruje

### ISSUE THREAD

**Issue by evapytlounova** [ParalelniPolis/hcpp2015main#30]
je to rusive predevsim na mobilu

![screenshot_2015-08-29_13 10 31](https://cloud.githubusercontent.com/assets/14018808/9561676/2789e836-4e50-11e5-894b-2a2d481d2853.png)

**Comment by pavelkraleu** [comment]
Vi nekdo jak to fixnout ?

**Comment by evapytlounova** [comment]
style="width: 100%; background: url(http://new.hcpp.cz/assets/images/content/HCPP_Web_Homepage_Picture.jpg) no-repeat top center fixed; min-height: 100%; height: 100%;"

? (alespon chrome konzole se tvari, ze takhle je to ok)

**Comment by tomtomklima** [comment]
Fajn, klidně to tam mrskni

**Comment by pavelkraleu** [comment]
Evo, rovnou tam prosim takove bugy opravuj, dost mozna mas vice webovych znalosti nez my vsichni dohromady, tak netreba otalet :)

Soubor ktery hledas je zde :
https://github.com/ParalelniPolis/hcpp2015main/blob/gh-pages/_layouts/default.html

**Comment by pavelkraleu** [comment]
@evapytlounova pridal jsem te do organizace PP

**Comment by evapytlounova** [comment]
ja sem za zivot napsala jeden a to pred vic jak deseti lety :) tohle je
cisty google. nicmene ted jsem doma a konecne to tam muzu dat :)

2015-08-30 20:50 GMT+02:00 Pavel Král notifications@github.com:

**Comment by evapytlounova** [comment]
mam na ten push prava? (remote: Permission to ParalelniPolis/hcpp2015main.git denied to evapytlounova.
fatal: unable to access 'https://github.com/ParalelniPolis/hcpp2015main.git/': The requested URL returned error: 403)

**Comment by pavelkraleu** [comment]
Furt si neprijala pozvani do repozitare :)
Podivej se do emailu
<img width="529" alt="screen shot 2015-08-31 at 01 31 06" src="https://cloud.githubusercontent.com/assets/4248287/9570103/2c6195c6-4f80-11e5-8639-2a8c7f515bd9.png">

**Comment by evapytlounova** [comment]
ah, ja sem si ho zkusene mazla v mobilu, tim se to cel vysvetluje. Plus jsem slepa. eh... dik

**Comment by evapytlounova** [comment]
done
