### ISSUE TITLE
mobil - menu nenaviguje

### ISSUE THREAD

**Issue by evapytlounova** [ParalelniPolis/hcpp2015main#32]
xiaomi, nativni browser

zadna z poloek menu me nikam neposune a stranka zustane tam, kde byla

**Comment by pavelkraleu** [comment]
Chrome na Androidu je v poradku

**Comment by evapytlounova** [comment]
opera na androidu 4.3 tez nic :) u chromu potvrzuju funkcnost.

**Comment by evapytlounova** [comment]
iphone a safari je taky ok, tak nevim... muzete to nekdo zkusit na androidu+opere pls?

**Comment by tomtomklima** [comment]
Opera na Androidu bohužel neumí, native browser ano - prohlásil bych to za neřešitelné (Opera ani Safari neumí kotvy). Někdo proti?

**Comment by evapytlounova** [comment]
V safari mi to funguje. Ale jo, souhlas, imho operu resit netreba

**Comment by pavelkraleu** [comment]
Prohlasme Operu za `unsupported` :)
