### ISSUE TITLE
Smuggler - Sehnat obrazek

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#49]

**Comment by Joockey** [comment]
Je to privacy extremist, takže nám svou fotku nepošle - co tam umístit tuto náhražku (stejně tak u Franka Brauna)?
![fotolia_50920378_subscription_xxl](https://cloud.githubusercontent.com/assets/9377701/9611051/cf6d55f8-50dd-11e5-8a40-fb6251445a2e.jpg)

**Comment by jakubsabata** [comment]
Co tam dát spíš Mfishovu grafiku hackera?

2015-09-01 21:21 GMT+02:00 Joockey notifications@github.com:

> Je to privacy extremist, takže nám svou fotku nepošle - co tam umístit
> tuto náhražku (stejně tak u Franka Brauna)?
> [image: fotolia_50920378_subscription_xxl]
> https://cloud.githubusercontent.com/assets/9377701/9611051/cf6d55f8-50dd-11e5-8a40-fb6251445a2e.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ParalelniPolis/hcpp2015main/issues/49#issuecomment-136832954
> .

## 

Jakub Šabata

mail: jakub.sabata@gmail.com
mobile: +420 605 817 668

**Comment by tomtomklima** [comment]
Mě se líbí jak je to všechno ve stejném stylu - reálné fotky

---
