### ISSUE TITLE
Dokoncit stranku recniku

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#5]
Stranka recniku nyni vypada takto :
<img width="666" alt="screen shot 2015-08-13 at 19 35 13" src="https://cloud.githubusercontent.com/assets/4248287/9256863/7604a132-41f2-11e5-8e3c-70856e1739e8.png">

Takto ji namaloval mFish
<img width="705" alt="screen shot 2015-08-13 at 19 37 29" src="https://cloud.githubusercontent.com/assets/4248287/9256904/c4dfb7b0-41f2-11e5-90eb-0474675197e0.png">

Takto ji ma nastylovanou Orlando
http://orlando.html.themeforest.createit.pl/light/portfolio-masonry.html

**Comment by MarekJCK** [comment]
Kolko tam bude hosti? Chcete aby to vyzeralo ako namaloval mfish alebo to ma byt ten masonry od orlanda?

**Comment by tomtomklima** [comment]
done
