### ISSUE TITLE
detail - sede pruhy u fotek recniku

### ISSUE THREAD

**Issue by evapytlounova** [ParalelniPolis/hcpp2015main#50]
vyska pruhu se odviji podle delky description, takze to obcas vypada trochu divoce - spis k zamysleni, jestli nechcem tu vysku treba dat fixni

![image](https://cloud.githubusercontent.com/assets/14018808/9575053/d6ac24dc-4fcc-11e5-9e2f-e9f284dc964d.png)

**Comment by tomtomklima** [comment]
Podle mfishe v pohodě, můžeš přeházit hosty aby to nevypadalo, ale asi bych to nechal
