### ISSUE TITLE
Bullshit popis u marady

### ISSUE THREAD

**Issue by Joockey** [ParalelniPolis/hcpp2015main#52]
Ahoj, nevim proč, ale i přesto, že v posts je marada správně jako tajemník Karla Janečka, tak na webu je jako programátor společnosti ness - to je jeho minulý zaměstnání. dal bych tam obojí

**Comment by tomtomklima** [comment]
@Joockey na žádost Romana jsem to na webu změnil - prý by to bylo moc provokující

**Comment by pavelkraleu** [comment]
Bylo to v Google Docs.

Jeste je to na detailu recnika :
http://hcpp.cz/speakers/marada.html
https://github.com/ParalelniPolis/hcpp2015main/blob/gh-pages/_posts/2015-08-28-cz_marada.md

http://hcpp.cz/speakers/eng/marada.html
https://github.com/ParalelniPolis/hcpp2015main/blob/gh-pages/_posts/2015-08-28-marada.md

**Comment by tomtomklima** [comment]
Změněno i v popisu
