### ISSUE TITLE
Neproklikatelnost ENG na mobilní verzi

### ISSUE THREAD

**Issue by tomtomklima** [ParalelniPolis/hcpp2015main#56]
via Deathcat na FB

**Comment by tomtomklima** [comment]
Koukal jsem na to, tohle je v ruby takže přehazuji na @pavelkraleu

**Comment by pavelkraleu** [comment]
Ne, neni to ruby :)
https://github.com/ParalelniPolis/hcpp2015main/commit/92e76544f1492289534ba0013aed09d7500acc0f

**Comment by tomtomklima** [comment]
Zrada, pardon :)
