### ISSUE TITLE
Pokud u speakeru neni doplnen detail > 404, napr. http://hcpp.cz/speakers/raftl.html

### ISSUE THREAD

**Issue by sipak** [ParalelniPolis/hcpp2015main#57]
neslo by to udelat nejak automaticky neklikatelny, pokud odkazovana stranka neexistuje stranka... z pohledu navstevnika je to klikaci loterie, ktera vetsinou vede na 404

**Comment by Joockey** [comment]
Když jsem zkoušel texty doplnit v postech a submitnul to, házelo mi to vždy chybu.

**Comment by pavelkraleu** [comment]
@tomtomklima nektere soubory byly ulozene v nejakem windowsim kodovani, coz rozbilo renderovani webu. Ukladej veskere soubory prosim v UTF-8
<img width="590" alt="screen shot 2015-09-13 at 02 32 18" src="https://cloud.githubusercontent.com/assets/4248287/9834586/50382e88-59c1-11e5-97e6-0945a9e2b2af.png">

**Comment by tomtomklima** [comment]
Jop, mám to nastavené ale občas se to přehází - dám si na to pozor, dík
