### ISSUE TITLE
Dokoncit kalendar

### ISSUE THREAD

**Issue by pavelkraleu** [ParalelniPolis/hcpp2015main#6]
Kalendar by mel mit podoby tabulky

Takto vypada :
<img width="693" alt="screen shot 2015-08-13 at 19 39 51" src="https://cloud.githubusercontent.com/assets/4248287/9256985/575c61ba-41f3-11e5-93c6-88a03131ecb5.png">

Takto ho chce mFish :
<img width="627" alt="screen shot 2015-08-13 at 19 40 36" src="https://cloud.githubusercontent.com/assets/4248287/9256981/52c05a3a-41f3-11e5-9643-f9e2ed4ed9bc.png">

**Comment by tomtomklima** [comment]
Myšlenka webu je střídání barev (bílá/černá), vzhledem k fotkám to zatím vyhovuje stávajíce, po změně fotek se toto stává aktuálním

**Comment by pavelkraleu** [comment]
Problem neni v barevnosti, ale v tom, ze do kalendare v tomto stavu nelze pridavat udalosti
