### ISSUE TITLE
Moc velké fotky

### ISSUE THREAD

**Issue by tomtomklima** [ParalelniPolis/hcpp2015main#60]
Jak @boriskalisky správně podotknul, moc velké fotky dost zdržují načítání celého webu - chtělo by to všechno vzít a zmenčit na únosnou míru (nejlépe asi na 300x300px)

**Comment by tomtomklima** [comment]
Asi na to můžeme alokovat nějakého stážistu, co třeba @evapytlounova nebo jakub?

**Comment by JakubSvobodaa** [comment]
Ahoj, velikosti obrázků upravit zvládnu. Udělám to klidně dnes po škole.

**Comment by tomtomklima** [comment]
Sup,a díky moc; btw v mailu máš pozvánku abys mohl začím, stačí ji přijmout @JakubSvobodaa

**Comment by pavelkraleu** [comment]
Diky za pomoc Jakube, opravdu velkych fotek je tam jen par, nemusis menit uplne vsechny
![screen shot 2015-09-16 at 13 50 55](https://cloud.githubusercontent.com/assets/4248287/9903920/262d139a-5c7a-11e5-83fa-a8f51e4ca819.png)

**Comment by tomtomklima** [comment]
A poprosím pohlídat is přesné oříznutí na čtverec (ono 300x300 moc jiných možností nedává, ale treba bednar.jpg není čtverec a potom to dělá bordel)

**Comment by JakubSvobodaa** [comment]
Jasně, budu to kontrolovat, včera jsem to nestihl, ale dneska jdu do Polis cca v 17:00 tak se na to pak vrhnu.

zatím!

**Comment by JakubSvobodaa** [comment]
První, co musim zjistit, je, kde ty fotky jsou.. kdybyste někdo mohli, klidně dejte vědět.

**Comment by pavelkraleu** [comment]
https://github.com/ParalelniPolis/hcpp2015main/tree/gh-pages/assets/images/speakers

**Comment by JakubSvobodaa** [comment]
jo už jsem to našel, dík!

**Comment by tomtomklima** [comment]
Fixed by @JakubSvobodaa
