### ISSUE TITLE
Přidat další sekci

### ISSUE THREAD

**Issue by tomtomklima** [ParalelniPolis/hcpp2015main#61]
Potřebuje sekci "Praktické" - třeba že se to bude konat v baráku polis, že většina speakerů bude v angličtině a tak. Přesný text dodá @boriskalisky; @pavelkraleu můžeme to zprocesovat? Potřebuju datovou strukturu a html dodělám; mělo by to být pod Vstupenkami nad Mapou

**Comment by tomtomklima** [comment]
https://docs.google.com/document/d/1rWKysDddw1IcrG2-duyrH-_6812bklm6ekFzYuIJB4M/edit by Boris

**Comment by tomtomklima** [comment]
https://docs.google.com/document/d/1rWKysDddw1IcrG2-duyrH-_6812bklm6ekFzYuIJB4M/edit by boris

**Comment by pavelkraleu** [comment]
Co pouzit stejnou rozklikavaci strukturu kterou ma Hub v Ceniku a FAQ ?
http://paperhub.cz/#pricelist

**Comment by tomtomklima** [comment]
Hej dobrý nápad, jen to chce roztáhnout do celý šířky - html klidně zvládnu večer, stačí mi řipravit datovou strukturu

**Comment by tomtomklima** [comment]
Fixed
