### ISSUE TITLE
Chybi nahledovy obrazek hcpp.cz pro sdileni na socialnich sitich

### ISSUE THREAD

**Issue by sipak** [ParalelniPolis/hcpp2015main#62]
dal bych tam bud plakat, nebo nejakej screen shot se speakerama, bohuzel se mi to nepodarilo udelat bez pocitadla

![plakat](https://cloud.githubusercontent.com/assets/4264782/9954980/a21c0eec-5ded-11e5-828f-77a0a622bc29.png)
![screenshot](https://cloud.githubusercontent.com/assets/4264782/9954988/ab44a740-5ded-11e5-82be-9302bf8db25a.png)

**Comment by tomtomklima** [comment]
Plakát? co? kam? na sociální sítě? Nebo myslíš opengraph který je tu někde taky otevřený?

**Comment by pavelkraleu** [comment]
Duplicate https://github.com/ParalelniPolis/hcpp2015main/issues/12
