### ISSUE TITLE
detail prednasejiciho otevirat implicitne v novem tabu

### ISSUE THREAD

**Issue by sipak** [ParalelniPolis/hcpp2015main#69]
prohlizeni detailu je peklo, protoze pri kazde <zpet> se reloaduji fotky a stranka skace => quickfix otevirat detail speakera defaultne v novem tabu

**Comment by tomtomklima** [comment]
Vnímám to jako nešvar stránek z 90. let, vyjádření pléna?

**Comment by sipak** [comment]
nesvar jsou stranky, ktery nejdou souvisle prochazet kvuli reloading, udelal bych to, na mobilu je to totalni peklo, kdyz uz se dostanes tam kam chces, jeden klik ti to znici

**Comment by tomtomklima** [comment]
fair point; snad se k tomu dostanu večer

**Comment by tomtomklima** [comment]
feature added
