### ISSUE TITLE
program - cz preklady needed

### ISSUE THREAD

**Issue by evapytlounova** [ParalelniPolis/hcpp2015main#73]
Solving the encryption keys exchange problem 

Name Readymade - change of identity and ownership of official documents 

SIGINT and Practical Covert Communication 

Project SAFE: Decentralized Internet Layer 

Philosophy of privacy and the essence of anonymity 

Beauty and mystery in parallel microworld 

Why Bitcoin stands above the law plus a technical and tactical analyses of an attempted governance coup on the network ('XT-coin') 

Past, present and future of hacking 

Bitcoin, the Blockchain, and Artists:  How Creative People Can Find Freedom Through Crypto 

Random Darknet Shopping Bots, Mail Art and Surveillance Algorithms

**Comment by Joockey** [comment]
Lze najít v profilech speakerů:
Řešení problému výměny šifrovacích klíčů
Name readymade - změna identity a vlastnictví úředních dokumentů
SIGINT a praktická utajená komunikace
Projekt SAFE: decentralizovaná vrstva internetu
Filozofie soukromí a podstata anonymity
Krása a tajemství paralelního mikrosvěta
Proč stojí Bitcoin nad právem? Technické a strategické analýzy snah o zvrat nadvlády nad sítí (XT coin)
Minulost, současnost a bucoucnost hackingu
Bitcoin, blockchain a umělci: jak mohou kreativní lidé nalézt svobodu skrze kryptování
Bot pro náhodné nakupování na darknetu, mail art a sledovací algorytmy

**Comment by evapytlounova** [comment]
cool, dik. jinak mi nejde commitovat, protoze nemam permission pushovat zmeny, tvrdi to jak git tak ta github appka, pokud na to muzete nekdo kouknout a vyresit to, tak to vecer commitnu spolecne s #74
