### ISSUE TITLE
program - prohozene cz/en nazvy

### ISSUE THREAD

**Issue by evapytlounova** [ParalelniPolis/hcpp2015main#74]
Life between hacking and art. Establishing hacking department at Art Academy and Crypto Desing Challenge project / Život mezi hackingem a uměním. Založení ateliéru Hackingu na umělecké akademii a projekt Crypto Design Challenge

Želvy až po zem: Sabotáž a bugdoor "od výroby" / Turtles all the way down: Sabotage & bugdoor by design 

+
u Petr Boháček (CZ) doplnit eng preklad "Diskuze: Co pro tebe znamená stát?"

**Comment by tomtomklima** [comment]
fixed

**Comment by tomtomklima** [comment]
sh - revertnul jsem, je to tvé :)

**Comment by evapytlounova** [comment]
fixed
