### ISSUE TITLE
PŘESUN SAAMO PAAL - Z NEDĚLE NA SOBOTU

### ISSUE THREAD

**Issue by Joockey** [ParalelniPolis/hcpp2015main#75]

**Comment by tomtomklima** [comment]
@Joockey na kdy?

**Comment by sipak** [comment]
je to zvyrazneno v rozpisu google sheets na SO 17h, ale je to Michal Paal

**Comment by tomtomklima** [comment]
done (in slave - mergeneme snad brzo)
