### ISSUE TITLE
barvy linku v programu

### ISSUE THREAD

**Issue by sipak** [ParalelniPolis/hcpp2015main#77]
- linky modra / fialova asi nejsou zamer (viz obr) > chceme ve stejne barve jako text nadpisu a beze zmeny barvy po kliknuti
- nektere nadpisy nejsou klikaci (jen detail), nektere nadpisy ano (vc. detailu)

**Comment by sipak** [comment]
![web](https://cloud.githubusercontent.com/assets/4264782/10212952/fde55b8e-6806-11e5-9b9f-28072c341f73.JPG)

**Comment by evapytlounova** [comment]
fixed, ale nektere linky nefunguji - issue 80 created
