### ISSUE TITLE
2016?

### ISSUE THREAD

**Issue by yangwao** [ParalelniPolis/hcpp2015main#81]
Kedy bude aspon novy web s infos a CFP ?

Chcem to pridat do https://github.com/yangwao/hacker-conferences ;)

**Comment by tomtomklima** [comment]
Řešíme to, ale teď prioritizujeme nový web polis - ovšem kdybys nám chtěl píchnout, nebráníme se, v logu to máme už přes měsíc

**Comment by yangwao** [comment]
A cim? resp kde su nejake viac info?

**Comment by tomtomklima** [comment]
Nejlepší bude když se zastavíš v úterý nebo čtvrtek a probereme to

**Comment by yangwao** [comment]
Nie som v Prahe, spiste to niekde na github napr :)

**Comment by pavelkraleu** [comment]
@yangwao Co konkretne bys chtel na webu mit ? Vice info o HCPP 2015 ?

**Comment by prusnak** [comment]
Pre zaciatok by stacil napriklad iba upravit datum, nic ine. Videl som tu stranku nasharovanu kade-tade a je tam datum minulorocnej edicie, nie aktualnej.

**Comment by tomtomklima** [comment]
Však myšlenka je nechat tyto stránky jak jsou, jen je posunout do hcpp.cz/2015 a na mainu založit komplet novou prezentaci

**Comment by Joockey** [comment]
Souhlas,

Pavle, mohli bychom se na to spoelčně podívat? Zatím tam dáme datum a krátký invite. Nějaké informace k HCPP2016 už mám, budeme tedy schopní launch page dát dohromady. Grafiku budeme řešit taky, ale nebudeme na ni čekat :)

M.

**Comment by pajasevi** [comment]
Kluci hlavně klid, tohle je pod kontrolou a čas na to je. Do úterý jsme
ještě ani nevěděli že HCPP už má datum. Nejdřív hodíme aktulní page do
složky /2015 a pak vyházíme obsah a možná malinko postylujem barvičky, aby
to vypadalo jinak.

Další úpravy na webu budeme řešit až to bude aktuální.

P.

Dne 4. března 2016 15:06 Joockey notifications@github.com napsal(a):

**Comment by sipak** [comment]
uz jsme to probirali v utery, cil je vytlacit to ven do dvou tydnu a vyuzit Andreasovi pritomnosti k tomu, aby se to zpropagovalo
